version-info:
  version-number: 0.1
  version-date: 20220429
sources:
  tz-info:
    #Name of github repo with the time zone data
    repository-name: evansiroky/timezone-boundary-builder
    #Release number of time zone data
    release: 2021c
  EPA-CEMS:
    URL-API: https://api.epa.gov/easey
    URL-hourly: ftp://newftp.epa.gov/DMDnLoad/emissions/hourly/monthly
    start-year: 1995
    end-year:
  EIA-Form923:
    URL: https://www.eia.gov/electricity/data/eia923
    start-year: 1999
    end-year:
  EIA-Form860:
    URL: http://www.eia.gov/electricity/data/eia860
    start-year: 1990
    end-year:
  NRC-RPSR:
    URL-base: https://www.nrc.gov/reading-rm/doc-collections/event-status/reactor-status/
    start-date: 1999-01-01
    end-date:
